modLoader = "javafml"
loaderVersion = "[36,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "peacegiver"
version = "${version}"
displayName = "PeaceGiver"
authors = "Kall"
description = '''
'''
#logoFile = ""

[[dependencies.peacegiver]]
modId="duplicationless"
mandatory=true
versionRange="[1.0.1,)"
ordering="NONE"
side="BOTH"